name: build rust

on:
  push:
  workflow_dispatch:

jobs:
  rust:
    name: "Build Rust"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install rust muslc
      run: |
        rustup toolchain install stable-x86_64-unknown-linux-musl
    - uses: Swatinem/rust-cache@v2
    - name: Build rust
      run: |
        cargo build -r --target=x86_64-unknown-linux-musl
    - name: upload binary
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        files: |
          target/x86_64-unknown-linux-musl/release/proc-mem-to-prom
          proc-mem-to-prom.service
